# Generated by Django 6.0.2 on 2026-02-23 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTeamSSHCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('team_name', models.CharField(blank=True, default='', max_length=120)),
                ('ssh_username', models.CharField(max_length=120)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('encrypted_private_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_global_team_ssh_keys_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'updated_at'], name='dash_gl_ssh_active_upd_idx'), models.Index(fields=['team_name', 'is_active'], name='dash_gl_ssh_team_active_idx')],
            },
        ),
    ]
