# Generated by Django 6.0.2 on 2026-02-24 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0002_remove_globalteamsshcredential_ssh_port_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uuid', models.CharField(max_length=64)),
                ('resource_name', models.CharField(blank=True, default='', max_length=255)),
                ('scope', models.CharField(choices=[('account', 'Account'), ('team', 'Team'), ('global', 'Global')], default='account', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_resource_access_grants_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_resource_access_grants', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_resource_access_grants', to='auth.group')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'scope'], name='dash_res_acc_owner_sc_ix'), models.Index(fields=['team', 'scope'], name='dash_res_acc_team_sc_ix')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'resource_uuid'), name='dash_res_acc_owner_uuid_ux')],
            },
        ),
    ]
