# Generated by Django 6.0.2 on 2026-02-24 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0003_resourceaccessgrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTeamShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uuid', models.CharField(max_length=64)),
                ('resource_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='resourceaccessgrant',
            name='dash_res_acc_owner_sc_ix',
        ),
        migrations.RemoveIndex(
            model_name='resourceaccessgrant',
            name='dash_res_acc_team_sc_ix',
        ),
        migrations.RemoveConstraint(
            model_name='resourceaccessgrant',
            name='dash_res_acc_owner_uuid_ux',
        ),
        migrations.AddField(
            model_name='resourceteamshare',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_resource_team_shares_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceteamshare',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_resource_team_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceteamshare',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_resource_team_shares', to='auth.group'),
        ),
        migrations.RemoveField(
            model_name='resourceaccessgrant',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='resourceaccessgrant',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='resourceaccessgrant',
            name='team',
        ),
        migrations.AddIndex(
            model_name='resourceteamshare',
            index=models.Index(fields=['owner', 'team'], name='dash_res_team_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourceteamshare',
            constraint=models.UniqueConstraint(fields=('owner', 'resource_uuid', 'team'), name='dash_res_team_owner_uuid_team_ux'),
        ),
        migrations.DeleteModel(
            name='ResourceAccessGrant',
        ),
    ]
