# Generated by Django 6.0.2 on 2026-02-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_systemsetup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalTeamAPIKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("team_name", models.CharField(blank=True, default="", max_length=120)),
                ("key_prefix", models.CharField(max_length=80)),
                ("key_hash", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_global_team_api_keys_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="globalteamapikey",
            index=models.Index(fields=["is_active", "updated_at"], name="dash_gl_api_active_upd_idx"),
        ),
        migrations.AddIndex(
            model_name="globalteamapikey",
            index=models.Index(fields=["team_name", "is_active"], name="dash_gl_api_team_active_idx"),
        ),
        migrations.AddIndex(
            model_name="globalteamapikey",
            index=models.Index(fields=["key_prefix"], name="dash_gl_api_prefix_idx"),
        ),
    ]
