# Generated by Django 6.0.2 on 2026-02-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_globalteamapikey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeatureAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feature_key", models.CharField(max_length=64)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_feature_access_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_feature_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["feature_key", "-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="userfeatureaccess",
            constraint=models.UniqueConstraint(fields=("user", "feature_key"), name="dash_user_feature_ux"),
        ),
        migrations.AddIndex(
            model_name="userfeatureaccess",
            index=models.Index(fields=["feature_key", "is_enabled"], name="dash_feat_key_enabled_idx"),
        ),
        migrations.AddIndex(
            model_name="userfeatureaccess",
            index=models.Index(fields=["user", "is_enabled"], name="dash_feat_user_enabled_idx"),
        ),
    ]
