# Generated by Django 6.0.2 on 2026-02-24 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0007_userfeatureaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=220, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('body_markdown', models.TextField(blank=True, default='')),
                ('body_html_fallback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_wiki_pages_created', to=settings.AUTH_USER_MODEL)),
                ('team_access', models.ManyToManyField(blank=True, related_name='dashboard_wiki_pages', to='auth.group')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_wiki_pages_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['path', '-updated_at'],
                'indexes': [models.Index(fields=['path'], name='dash_wiki_path_idx'), models.Index(fields=['updated_at'], name='dash_wiki_updated_idx')],
            },
        ),
    ]
