# Generated by Django 6.0.2 on 2026-02-24 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0008_wikipage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['is_draft', 'updated_at'], name='dash_wiki_draft_upd_idx'),
        ),
    ]
