# Generated by Django 6.0.2 on 2026-02-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_resourceroutealias'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetup',
            name='default_model',
            field=models.CharField(blank=True, default='gpt-4.1-mini', max_length=120),
        ),
        migrations.AddField(
            model_name='systemsetup',
            name='maintenance_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetup',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetup',
            name='monitoring_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
