# Generated by Django 6.0.2 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_systemsetup_microsoft_login_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetup",
            name="github_login_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
