# Generated by Django 6.0.2 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_systemsetup_ask_github_mcp_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="resource_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="resource_uuid",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="scope",
            field=models.CharField(
                choices=[("workspace", "Workspace"), ("resource", "Resource")],
                default="workspace",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="wikipage",
            name="path",
            field=models.CharField(max_length=220),
        ),
        migrations.AddConstraint(
            model_name="wikipage",
            constraint=models.UniqueConstraint(
                fields=("scope", "resource_uuid", "path"),
                name="dash_wiki_scope_res_path_ux",
            ),
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(fields=["scope", "resource_uuid", "path"], name="dash_wiki_scope_res_path_idx"),
        ),
        migrations.AddIndex(
            model_name="wikipage",
            index=models.Index(fields=["scope", "updated_at"], name="dash_wiki_scope_upd_idx"),
        ),
    ]
