# Generated by Django 6.0.2 on 2026-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_seed_alshival_sdk_handoff_wiki"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wikipage",
            name="scope",
            field=models.CharField(
                choices=[("workspace", "Workspace"), ("team", "Team"), ("resource", "Resource")],
                default="workspace",
                max_length=16,
            ),
        ),
    ]
