# Generated by Django 6.0.2 on 2026-02-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_wikipage_team_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikipage',
            options={'ordering': ['scope', 'resource_uuid', 'path', '-updated_at']},
        ),
    ]
