from django.urls import path

from . import views

urlpatterns = [
    path('setup/', views.setup_welcome, name='setup_welcome'),
    path('', views.home, name='home'),
    path('calendar/cache/refresh/', views.refresh_calendar_cache, name='refresh_calendar_cache'),
    path('calendar/asana/tasks/<str:task_gid>/complete/', views.update_asana_task_completion, name='update_asana_task_completion'),
    path('calendar/asana/boards/<str:board_gid>/tasks/create/', views.create_asana_board_task, name='create_asana_board_task'),
    path('calendar/asana/tasks/<str:task_gid>/delete/', views.delete_asana_task, name='delete_asana_task'),
    path('calendar/asana/tasks/<str:task_gid>/comments/', views.list_asana_task_comments, name='list_asana_task_comments'),
    path('calendar/asana/tasks/<str:task_gid>/comments/add/', views.add_asana_task_comment, name='add_asana_task_comment'),
    path('calendar/asana/tasks/<str:task_gid>/subtasks/', views.list_asana_task_subtasks, name='list_asana_task_subtasks'),
    path('calendar/asana/tasks/<str:task_gid>/assign/', views.update_asana_task_assignee, name='update_asana_task_assignee'),
    path('calendar/asana/tasks/<str:task_gid>/dependencies/', views.list_asana_task_dependencies, name='list_asana_task_dependencies'),
    path('calendar/asana/tasks/<str:task_gid>/dependencies/add/', views.add_asana_task_dependency, name='add_asana_task_dependency'),
    path('calendar/asana/tasks/<str:task_gid>/dependencies/remove/', views.remove_asana_task_dependency, name='remove_asana_task_dependency'),
    path('calendar/asana/tasks/<str:task_gid>/attachments/', views.list_asana_task_attachments, name='list_asana_task_attachments'),
    path('calendar/asana/boards/<str:board_gid>/sections/', views.list_asana_project_sections, name='list_asana_project_sections'),
    path('calendar/asana/boards/<str:board_gid>/status/', views.get_asana_project_status, name='get_asana_project_status'),
    path('calendar/asana/boards/<str:board_gid>/webhook/register/', views.register_asana_webhook, name='register_asana_webhook'),
    path('calendar/asana/sections/<str:section_gid>/add-task/', views.move_asana_task_to_section, name='move_asana_task_to_section'),
    path('calendar/asana/workspaces/<str:workspace_gid>/members/', views.list_asana_workspace_members, name='list_asana_workspace_members'),
    path('calendar/asana/webhook/receive/', views.receive_asana_webhook, name='receive_asana_webhook'),
    path('calendar/asana/boards/<str:board_gid>/resources/update/', views.update_asana_board_resource_mapping, name='update_asana_board_resource_mapping'),
    path('calendar/asana/tasks/<str:task_gid>/resources/update/', views.update_asana_task_resource_mapping, name='update_asana_task_resource_mapping'),
    path('calendar/agenda/items/resources/update/', views.update_overview_agenda_item_resource_mapping, name='update_overview_agenda_item_resource_mapping'),
    path(
        'calendar/alerts/settings/update/',
        views.update_overview_calendar_notification_settings,
        name='update_overview_calendar_notification_settings',
    ),
    path('notifications/', views.notifications_feed, name='notifications_feed'),
    path('notifications/read-all/', views.notifications_mark_all_read, name='notifications_mark_all_read'),
    path('notifications/clear-all/', views.notifications_clear_all, name='notifications_clear_all'),
    path('search/kb/', views.search_kb_suggestions, name='search_kb_suggestions'),
    path('settings/', views.app_settings, name='app_settings'),
    path(
        "settings/account/connectors/<str:provider>/disconnect/",
        views.disconnect_social_connector,
        name="disconnect_social_connector",
    ),
    path('settings/connectors/', views.connector_settings, name='connector_settings'),
    path('settings/admin/', views.alshival_admin, name='alshival_admin'),
    path('settings/api-keys/account/create/', views.create_account_api_key_item, name='create_account_api_key_item'),
    path('wiki/', views.wiki, name='wiki'),
    path('team/', views.team_page, name='team_page'),
    path('wiki/editor/new/', views.wiki_editor_new, name='wiki_editor_new'),
    path('wiki/editor/<int:page_id>/', views.wiki_editor, name='wiki_editor'),
    path('wiki/pages/create/', views.wiki_create_page, name='wiki_create_page'),
    path('wiki/pages/<int:page_id>/update/', views.wiki_update_page, name='wiki_update_page'),
    path('wiki/pages/<int:page_id>/delete/', views.wiki_delete_page, name='wiki_delete_page'),
    path('team-directory/', views.team_directory, name='team_directory'),
    path('team-directory/teams/create/', views.team_directory_create_team, name='team_directory_create_team'),
    path('team-directory/teams/<int:team_id>/rename/', views.team_directory_rename_team, name='team_directory_rename_team'),
    path('team-directory/teams/<int:team_id>/delete/', views.team_directory_delete_team, name='team_directory_delete_team'),
    path('team-directory/teams/<int:team_id>/members/update/', views.team_directory_update_team_members, name='team_directory_update_team_members'),
    path('team-directory/teams/<int:team_id>/members/add/', views.team_directory_add_team_member, name='team_directory_add_team_member'),
    path('team-directory/teams/<int:team_id>/members/<int:user_id>/remove/', views.team_directory_remove_team_member, name='team_directory_remove_team_member'),
    path('team-directory/users/create/', views.team_directory_create_user, name='team_directory_create_user'),
    path('team-directory/users/<int:user_id>/update/', views.team_directory_update_user, name='team_directory_update_user'),
    path('team-directory/users/<int:user_id>/delete/', views.team_directory_delete_user, name='team_directory_delete_user'),
    path('team-directory/users/<int:user_id>/permissions/', views.team_directory_update_user_permissions, name='team_directory_update_user_permissions'),
    path('team-directory/users/invite/preview/', views.team_directory_invite_preview, name='team_directory_invite_preview'),
    path('team-directory/users/invite/', views.team_directory_invite_user, name='team_directory_invite_user'),
    path('invites/<str:token>/', views.accept_user_invite, name='accept_user_invite'),
    path('invites/<str:token>/complete/', views.complete_user_invite, name='complete_user_invite'),
    path('resources/', views.resources, name='resources'),
    path('resources/ssh-keys/add/', views.add_ssh_credential_item, name='add_ssh_credential_item'),
    path('resources/ssh-keys/<str:credential_id>/delete/', views.delete_ssh_credential_item, name='delete_ssh_credential_item'),
    path('resources/ssh-keys/global/<int:credential_id>/delete/', views.delete_global_ssh_credential_item, name='delete_global_ssh_credential_item'),
    path('u/<str:username>/resources/<str:resource_uuid>/logs/', views.resource_logs_ingest, name='resource_logs_ingest'),
    path('team/<str:team_name>/resources/<str:resource_uuid>/logs/', views.team_resource_logs_ingest, name='team_resource_logs_ingest'),
    path('u/<str:username>/resources/<uuid:resource_uuid>/notes/add/', views.resource_note_add, name='resource_note_add'),
    path('team/<str:team_name>/resources/<uuid:resource_uuid>/notes/add/', views.team_resource_note_add, name='team_resource_note_add'),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/notes/attachments/<int:attachment_id>/',
        views.resource_note_attachment,
        name='resource_note_attachment',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/notes/attachments/<int:attachment_id>/',
        views.team_resource_note_attachment,
        name='team_resource_note_attachment',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/check/',
        views.check_resource_health_detail,
        name='check_resource_health_detail',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/ping-stream/',
        views.resource_ping_stream,
        name='resource_ping_stream',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/check/',
        views.team_check_resource_health_detail,
        name='team_check_resource_health_detail',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/ping-stream/',
        views.team_resource_ping_stream,
        name='team_resource_ping_stream',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/alerts/settings/update/',
        views.update_resource_alert_settings,
        name='update_resource_alert_settings',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/alerts/settings/update/',
        views.team_update_resource_alert_settings,
        name='team_update_resource_alert_settings',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/api-keys/create/',
        views.create_resource_api_key_item,
        name='create_resource_api_key_item',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/api-keys/create/',
        views.team_create_resource_api_key_item,
        name='team_create_resource_api_key_item',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/api-keys/<int:key_id>/revoke/',
        views.revoke_resource_api_key_item,
        name='revoke_resource_api_key_item',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/api-keys/<int:key_id>/revoke/',
        views.team_revoke_resource_api_key_item,
        name='team_revoke_resource_api_key_item',
    ),
    path('u/<str:username>/resources/<uuid:resource_uuid>/wiki/', views.resource_wiki, name='resource_wiki'),
    path('team/<str:team_name>/resources/<uuid:resource_uuid>/wiki/', views.team_resource_wiki, name='team_resource_wiki'),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/wiki/editor/new/',
        views.resource_wiki_editor_new,
        name='resource_wiki_editor_new',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/wiki/editor/new/',
        views.team_resource_wiki_editor_new,
        name='team_resource_wiki_editor_new',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/wiki/editor/<int:page_id>/',
        views.resource_wiki_editor,
        name='resource_wiki_editor',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/wiki/editor/<int:page_id>/',
        views.team_resource_wiki_editor,
        name='team_resource_wiki_editor',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/wiki/pages/create/',
        views.resource_wiki_create_page,
        name='resource_wiki_create_page',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/wiki/pages/create/',
        views.team_resource_wiki_create_page,
        name='team_resource_wiki_create_page',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/wiki/pages/<int:page_id>/update/',
        views.resource_wiki_update_page,
        name='resource_wiki_update_page',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/wiki/pages/<int:page_id>/update/',
        views.team_resource_wiki_update_page,
        name='team_resource_wiki_update_page',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/wiki/pages/<int:page_id>/delete/',
        views.resource_wiki_delete_page,
        name='resource_wiki_delete_page',
    ),
    path(
        'u/<str:username>/resources/<uuid:resource_uuid>/wiki/sync/',
        views.resource_wiki_sync,
        name='resource_wiki_sync',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/wiki/pages/<int:page_id>/delete/',
        views.team_resource_wiki_delete_page,
        name='team_resource_wiki_delete_page',
    ),
    path(
        'team/<str:team_name>/resources/<uuid:resource_uuid>/wiki/sync/',
        views.team_resource_wiki_sync,
        name='team_resource_wiki_sync',
    ),
    path('u/<str:username>/resources/<uuid:resource_uuid>/', views.resource_detail, name='resource_detail'),
    path('team/<str:team_name>/resources/<uuid:resource_uuid>/', views.team_resource_detail, name='team_resource_detail'),
    path('resources/add/', views.add_resource_item, name='add_resource_item'),
    path('resources/<int:resource_id>/edit/', views.edit_resource_item, name='edit_resource_item'),
    path('resources/<int:resource_id>/delete/', views.delete_resource_item, name='delete_resource_item'),
    path('resources/<int:resource_id>/check/', views.check_resource_health, name='check_resource_health'),
    path('team/chat/messages/', views.team_chat_messages, name='team_chat_messages'),
    path('team/chat/ask/', views.ask_alshival_team_chat, name='ask_alshival_team_chat'),
    path('team/chat/attachments/<int:team_id>/<int:attachment_id>/', views.team_chat_attachment, name='team_chat_attachment'),
    path('team/chat/alerts/settings/update/', views.update_team_chat_notification_settings, name='update_team_chat_notification_settings'),
    path('twilio/sms', views.twilio_sms_webhook, name='twilio_sms_webhook'),
    path('twilio/sms/', views.twilio_sms_webhook),
    path('twilio/sms-group', views.twilio_sms_group_webhook, name='twilio_sms_group_webhook'),
    path('twilio/sms-group/', views.twilio_sms_group_webhook),
    path('chat/widget/', views.ask_alshival_widget_page, name='ask_alshival_widget_page'),
    path('chat/session-greeting/', views.ask_alshival_session_greeting, name='ask_alshival_session_greeting'),
    path('chat/history/', views.ask_alshival_chat_history, name='ask_alshival_chat_history'),
    path('chat/history/clear/', views.ask_alshival_clear_chat_history, name='ask_alshival_clear_chat_history'),
    path('chat/ask/', views.ask_alshival_chat, name='ask_alshival_chat'),
    path('chat/voice-token/', views.ask_alshival_voice_token, name='ask_alshival_voice_token'),
    path('chat/voice-log/', views.ask_alshival_voice_log, name='ask_alshival_voice_log'),
]
